### ISSUE TITLE
Cant seem to run 

### ISSUE THREAD

**Issue by MiguelAReis** [pmonta/gerber2graphtec#20]
When I run 
`/gerber2graphtec examples/test_0.5mm_0402.gbr >/dev/usb/lp`
I get the following:

`0
Traceback (most recent call last):
  File "./gerber2graphtec", line 117, in <module>
    strokes = pic.read_pic(temp_pic)
  File "/home/miguel/Desktop/gerber2graphtec/gerber2graphtec/pic.py", line 5, in read_pic
    f = open(filename,"r")
IOError: [Errno 2] No such file or directory: '_tmp_gerber.pic'
`

And the plotter just goes back and forth a few times

**Comment by prototypicall** [comment]
Make sure 'pstoedit' and 'gerbv' are available on your machine. gerber2graphtec attempts to invoke these to convert to gerber files to a format it understands but does not show anything if these applications are not available. You can install them with 'sudo apt install <application>', etc. depending on your linux distro.
